pub.pzdcdoc.org - пример, настроить CI,
 - сделать пример для pzdcdoc.org
- Статьи из Google просто слинковать.
- GIT конфигурация и команды
- BGBilling
- 

Странная эволюция

Раньше ОС, в ней программы. Потом браузерная версия, жрущая.
Потом мобильная браузерная, нативные мобильные.
Show running WhatsApp Web comparing to Thunderbird, Office mobile and local.
Вкладки вместо окон и мы получили ОС в ОС. При этом MDI приложения типа Photoshop куда удобнее.
Не было бы лучше ставить просто в Windows программы как из Линукс?

== Связанность - это хорошо

связанность данных и целостность, как понять, какие целы
JSP и Java класс
Микроядерная ОС, Линус правильно высказался.

== Как масштабируются туалеты

Туалет в госцирке
вечная мечта о масштабировании и резервировании, раньше оракл на этом зарабатывал
докеры и кубернетисы
микросервисы
забывают о данных, подходит только для стейтлесс, а таких задач совсем мало


// Унификация
// Введение // Ссылки
// Среда разработки
// GIT, консоль
// Дистрибутивы, SSL
// Обзор языков
// Системы сборки
// FAR
// SSH
// NGINX
// Хостинги
// Server-side vs client-side
// Документация
// Методика работы с файлами
