= IDE
:toc:

Опыт работы с различными IDE.

== VS Code
Реализована на JavaScript / TypeScript, платформа Electron.

=== Преимущества
[square]
* очень быстрая, потребляет сравнительно мало ресурсов;
* поддержка множества языков: Java Script распознаёт сложные конструкции, навигация, удобна для проектов с многими языками;
* удобный поиск операций по `Ctrl + Shift P` или файлов по `Ctrl + P`; 
* вся конфигурация хранится в файлах, вообще IDE всё видит как файлы и каталоги, без дополнительных понятий, можно спокойно работать с проектами в workspace от Eclipse, например; 
* открывать каталоги проектов можно как вместе в виде workspace, так и по отдельности.

=== Недостатки
[square]
* инструменты работы с GIT: получить версию файла из каммита;
* к концепции интерфейса, когда каждая операция в отдельном списке слева надо привыкать;
* по сравнению с Eclipse почти нет поддержки JSP;
* фукнции рефакторинга Java хуже, чем в Eclipse: при копировании кода не прихыватывает импорты.

== Eclipse
=== Преимущества
[square]
* есть всё ""
<<TODO>>
