= Введение
:toc:

[[about]]
== На хера козе баян?
В этой книге я собираю свой многолетний (с 2002) опыт в области разработки ПО.
Для меня это место изложения своей точки зрения по различным вопросам, без необходимости делать это много раз повторно, плюс сборник практических заметок.
В отличие от блога, данное повествования я надеюсь держать в некой структурированной и актуальной форме, позволяющей последовательное изучение.
Но для возможности отслеживания изменений присутствует <<changes.adoc#, лог>>.

Мнение моё, разумеется, субъективно и полностью основывается на собственном опыте и его интерпретации.
Посему было бы интересно выслушать других разработчиков, а также вопросы начинающих, что можно сделать понятнее в этом link:https://t.me/bgerp[Telegram канале].

[[howto-write]]
== Как дописать
Книжка пишется открытым способом в link:https://github.com/Pingvin235/book[GitHub], 
Для сборки у себя - клонируйте репозитарий и выполните внутри него скрипт `gradlew`.
Вам понадобится установленная Java 11 в системе.

Ваши изменений можно оформить в произвольно называющуюся ветку и послать Merge request (в GitHub он называется Pull request).

[[language]]
== Какой язык выбрать?
На этот традиционный вопрос и правильный вопрос я тоже когда-то искал ответ, а в последнее время начал отвечать сам.
Логичное свойство человека разумного состоит в сбережении энергии на изучение только самого нужного. 

=== Плохая новость
// TODO: структура познания
Не получится обойтись одним языком, вокруг каждого из них роится толпа знаний и технологий, которые тянут друг друга и постоянно меняются.

Например, в своём CV я помещал примерно следующий список, разделив домены на хорошо известные и просто знакомые.
----
Huge hands-on experience in domains:
- Agile SCRUM / SAFe / Kanban development, TDD, Continuous Delivery;
- Development process tools: JIRA, YouTrack, Jenkins, GitLab (CI);
- Software documentation: WiKi, DocBook, Confluence, AsciiDoctor;
- Databases: MySQL, Oracle, PostgreSQL, Elastic Search;
- Development of heavily loaded systems;
- Java SE development: Swing, java.lang, Utils, Collections, Networking, IO, JDBC, Concurrency;
- J2EE development: JSP, JSTL, Servlets, Struts, Tomcat;
- Web-applications: HTML, CSS, JS, JQuery, Angular;
- Network technologies, protocols;
- OS using and configuring: Linux, Windows, MacOS;
- Version control systems: GIT, SVN, CVS;
- Application lifecycle technologies: Gradle, Maven, Ant;
- Test frameworks: TestNG, JUnit, Mockito;
- Technologies: XML, XSD, XSLT, JSON, JSON-RPC, JAX-WS;
- Virtualization: WLS, Docker, VmWare, VirtualBox;
- Java related technologies: JavaMail, Log4j, Apache FOP, Xalan, Xerces, JEXL, JLDAP, Jasper Reports, iText, ActiveMQ;
- Development process tools: Jira, YouTrack, Jenkins, GitLab (CI), Sonar Cube;
- Linux server administration: Nginx, Apache, SSH, etc.;
- Modern Microsoft O365 stack: Azure AD, SharePoint, Exchange, OneDrive, Teams;
- IDE: VS Code, Eclipse, WebStorm, Idea, Android Studio.

Known domains:
- Mobile applications development for Android;
- Web-applications: TypeScript, React-JS, NodeJS;
- C++, C# development (Visual Studio);
- Microcontrollers programming: ATMEL;
- BASH/Perl/Python/PHP/Power Shell scripting, CGI scripts;
- Databases: LDAP, MongoDB, Sphinx;
- Java related technologies: Hibernate, Spring, JSF, JavaMail, Log4j, Apache FOP, Xalan, Xerces, JEXL, JLDAP, Jasper Reports, iText, ActiveMQ.
----

Со всем этим в той или иной мере мне приходилось сталкиваться и у любого профессионала портянка будет не меньше.

=== Хорошая новость
Базовые принципы и концепции очень похожи и каждый следующий язык или технология будут даваться всё проще.

// TODO: Самый уродливый из языков.

// TODO: Алгоритмы.

// TODO: Эволюция.

== Bash


=== Какой-никакой выбор
[[language-system]]
Традиционно языки программирования разделялись на системные и прикладные.
Место первого давно и успешно занимает *C* - на нём реализованы практически все операционные системы,
и системное ПО в них. По правде говоря, на нём и его объектном расширении *С++* же уже давно написано почти всё возможное прикладное ПО: 
игры, редакторы, пакеты моделирования и т.п. Но в силу разных факторов: моды, передела рынка периодически возникают всё новые 
языки, обещающие быстрый невероятный результат при полном идиотизме разработчика.

Основная причина бума языков и технологий в целом - низкий порог вхождения. Будь то дружелюбный интерфейс Windows, построитель форм или 
даже целых программ "движением мыши, которое может совершить любая секретарша". К моменту появления принципиальных недостатков на корявой технологии уже слишком много написано и завязано, отступать уже некуда.

// TODO: Тип или не тип.
// TODO: Мусор или нет.

==== Web-стек: Java Script/HTML/CSS
Начавшись как средство создания лёгкой анимации в языке разметки HTML, Java Script распространился сейчас везде.
В общем-то на нём и его типизированной обёртке Type Script можно писать любые приложения, он занял нишу, когда-то отводящуюся Java.
Избежать этой троицы в ближайшие лет сто на этой планете как будто не удасться, поэтому возможно хорошие кандидаты для начального изучения.
На https://jsfiddle.net/ можно легко поиграться и поставить первые эксперименты.

Не стоит, однако, сильно увекаться Java Script. Я рекомендую оставить его только для простых манипуляций DOM деревом и отправки AJAX запросов на клиенте. Все вычисление, работу с данными и формирование HTML блоков - выполнять на сервере.

// TODO: Server side rendering.

// https://t.me/bgerp/3264
==== Специальные языки вроде 1C либо SAP ABI
Из названия понятно, что ниша их узка и в общем-то нет никакого основания использовать вместо современных более распространённых языков.

==== Python 
Язык занял место Perl в среде скриптовых языков и повсеместно используется для решения задач мелкой автоматизации на серверах.
Этакий продвинутый Bash, более строгий и читаемый. Из недостатков можно заметить бардак с несовместимым переходом со 2 на 3 версию.

==== Java
Система пакетов, строгая типизация, консервативное развитие без катаклизмов долгие годы. Был момент неопределённости, когда создавшая язык компания Sun Microsystems была поглощена Oracle. Но как будто он успешно миновал и разработка передана сообществу. 

В настоящий момент Java де-факто стандарт приложениях, где не особенно критична производительность и не требуется обработки больших данных. Взамен потери производительности он предлагает существенно более высокую скорость разработки и безопасность по сравнению с <<#language-system, системными>> языками.
Когда-то он задумывался быть везде: апплеты на Web страницах, десктоп приложения, даже игры и специализированное железо. 
Остался в итоге в корпоративном секторе заменителем Кабола и на мобильных устройствах Android.

// TODO: Память на мелких объектов.

// TODO: Java based.

Cсылка на неплохую книжку по Java для начала изучения: http://www.fandroid.info/tutorial-po-osnovam-yazyka-programmirovaniya-java-dlya-nachinayushhih/

А здесь среда разработки в браузере: https://www.compilejava.net
