= Введение
:toc:

[[about]]
== О книге
Данная книга представляет из себя базу знаний по IT технологиям наподобии WiKi,
но пишется открытым способом в link:https://github.com/Pingvin235/book[GitHub].

Для сборки у себя - клонируйте репозитарий и выполните внутри него скрипт `gradlew`.
Вам понадобится установленная Java 11 в системе.

Ваши изменений можно оформить в произвольно называющуюся ветку и послать Merge request (в GitHub он называется Pull request).

Не готовые статьи вести в отдельных ветках, создав каталог автора под них. Они будут доступны при публикации по прямым
ссылкам, что даёт возможность обсуждения. После завершения статью - включать в оглавление и делать *merge squash* на
master ветку. 

Публикация производится скриптом `publish.bat`, для её возможности передайте https://t.me/pingvin235[Pingvin235] 
либо любому другому автору ваш открытый ключ.

Для отслеживания изменений присутствует <<changes.adoc#, лог>>.

== Рекомендации по правке
Если где-то в Сети уже есть хорошее руководство - проще разместить ссылку на него.
Для предотвращения утери в будущем - можно использовать https://archive.is/.
Пример сохранённой ссылки на https://archive.is/wip/TJsIF[https://bgerp.ru]

