= Введение
:toc:

[[about]]
== О книге
Данная книга представляет из себя базу знаний по IT технологиям наподобии Wiki,
но пишется открытым способом в link:https://github.com/Pingvin235/book[GitHub].

Падшая link:https://web.archive.org/web/20180201134441/http://wiki.bitel.ru/index.php/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0[Wiki BiTel] из архива.

Для сборки у себя - клонируйте репозитарий и выполните внутри него скрипт `gradlew`.
Вам понадобится установленная Java 11 в системе.

Ваши изменений можно оформить в произвольно называющуюся ветку и послать Merge request (в GitHub он называется Pull request).

Не готовые статьи вести в отдельных ветках, создав каталог автора под них. Они будут доступны при публикации по прямым
ссылкам, что даёт возможность обсуждения. После завершения статью - включать в оглавление и делать *merge squash* на
master ветку. 

Публикация производится скриптом `publish.bat`, для её возможности передайте https://t.me/pingvin235[Pingvin235] 
либо любому другому автору ваш открытый ключ.

Для отслеживания изменений присутствует <<changes.adoc#, лог>>.

== Рекомендации авторам
Если где-то в Сети уже есть хорошее руководство - проще разместить ссылку на него.
Для предотвращения утери в будущем - можно использовать https://archive.is/.
Пример сохранённой ссылки на https://archive.is/wip/TJsIF[https://bgerp.ru]

Избегайте больших файлов, они увеличивают размер GIT.

Генерация производится утилитой link:https://github.com/Pingvin235/pzdcdoc[PzdcDoc], здесь можно посмотреть link:https://pzdcdoc.org/demo/src/doc/demo.html[примеры] разметки, там же есть ссылка на исходный файл AsciiDoc.

